version: '2'

volumes:
  jenkins_home: ~

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: always
  slave:
    build:
      context: .
      dockerfile: ./slave/Dockerfile
    restart: always
    command: -url "$MASTER_URL" -workDir=/home/jenkins/agent "$AGENT_SECRET" agent-dind
