version: '2'

volumes:
  jenkins_home: ~

services:
  jenkins:
    image: jenkins/jenkins
    ports:
      - "80:8080"
      - "50000:50000"
    volumes:
      - $HOME/jenkins/.ssh:/var/jenkins_home/.ssh:ro
      - jenkins_home:/var/jenkins_home
    restart: always
  slave:
    build:
      context: ./slave
      dockerfile: ./Dockerfile
    restart: always
    privileged: true    
    volumes:
      - $HOME/jenkins/.ssh:/home/jenkins/.ssh:ro
    command: sh -c 'docker-entrypoint.sh dockerd &>/dev/null & sudo -u jenkins jenkins-slave -url "$MASTER_URL" -workDir=/home/jenkins/agent "$AGENT_SECRET" agent-dind'
